version: '3.8'

services:
  dcxuserbot:
    build: .
    container_name: apex_userbot
    restart: always
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
